// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWx-Wc086NXte5Azlp9hdvoMZvgbFWYKQ',
    appId: '1:69431892379:web:ad1d9da3290940310da93e',
    messagingSenderId: '69431892379',
    projectId: 'college-space-5940f',
    authDomain: 'college-space-5940f.firebaseapp.com',
    storageBucket: 'college-space-5940f.appspot.com',
    measurementId: 'G-T62LZE8XJ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlHz7tJGVRbjsvHzHqXrsmXLJnM2T2wRA',
    appId: '1:69431892379:android:f1a94132790bf1440da93e',
    messagingSenderId: '69431892379',
    projectId: 'college-space-5940f',
    storageBucket: 'college-space-5940f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRMSa8kJiXlFb7vLL3Imc2odwI9v62fdY',
    appId: '1:69431892379:ios:0a9f6cdf79e79a560da93e',
    messagingSenderId: '69431892379',
    projectId: 'college-space-5940f',
    storageBucket: 'college-space-5940f.appspot.com',
    iosBundleId: 'com.college.space.collegeSpace',
  );
}
