name: college_space
description: An application for college students where they can get there notes, timetable, etc. related their courses which helps them in their studies.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  device_preview: ^1.1.0
  flutter:
    sdk: flutter
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Bevan
      fonts:
        - asset: assets/fonts/Bevan-Regular.ttf
    - family: Blinker
      fonts:
        - asset: assets/fonts/Blinker-Regular.ttf
    - family: Biryani
      fonts:
        - asset: assets/fonts/Biryani-Regular.ttf