name: college_space
description: An application for college students where they can get there notes, timetable, etc. related their courses which helps them in their studies.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  device_preview: ^1.1.0
  firebase_analytics: ^10.7.1
  firebase_auth: ^4.14.1
  firebase_core: ^2.23.0
  firebase_database: ^10.3.5
  firebase_remote_config: ^4.3.5
  firebase_storage: ^11.5.2
  flutter:
    sdk: flutter
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Bevan
      fonts:
        - asset: assets/fonts/Bevan-Regular.ttf
    - family: Blinker
      fonts:
        - asset: assets/fonts/Blinker-Regular.ttf
    - family: Biryani
      fonts:
        - asset: assets/fonts/Biryani-Regular.ttf