name: college_space
description: An application for college students where they can get there notes, timetable, etc. related their courses which helps them in their studies.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  device_preview: ^1.1.0
  firebase_analytics: ^11.3.3
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_database: ^11.1.4
  firebase_remote_config: ^5.1.3
  firebase_storage: ^12.3.2
  flutter:
    sdk: flutter
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Bevan
      fonts:
        - asset: assets/fonts/Bevan-Regular.ttf
    - family: Blinker
      fonts:
        - asset: assets/fonts/Blinker-Regular.ttf
    - family: Biryani
      fonts:
        - asset: assets/fonts/Biryani-Regular.ttf